<ul class="help-box">
    <li>
        <div class="roundedcornr_box_867993">
            <div class="roundedcornr_top_867993"><div></div></div>
            <div class="roundedcornr_content_867993">
                <img src="<?php echo $this->baseUrl() . '/assets/images/Info.png' ?>" />
                <h3><fb:intl>The Rules</fb:intl></h3>
                <div class="box-content">
                    <p><fb:intl>You can enter up until the start of qualifying on the Saturday before each race.</fb:intl></p>
                    <p><fb:intl>Your lowest 3 scores are discarded. This means even if you miss a few races you can still win!</fb:intl></p>
                    <p><fb:intl>At the end of the year the player with the most points wins.</fb:intl></p>
                </div>
            </div>
            <div class="roundedcornr_bottom_867993"><div></div></div>
        </div>
    </li>
    <li>
        <div class="roundedcornr_box_867993">
            <div class="roundedcornr_top_867993"><div></div></div>
            <div class="roundedcornr_content_867993">
                <img src="<?php echo $this->baseUrl() . '/assets/images/Edit.png' ?>" />
                <h3><fb:intl>The Points</fb:intl></h3>
                <div class="box-content">
                    <p><fb:intl>Points are awarded after each race. The maximum number of points per race is 78 and they are awarded like this:</fb:intl></p>
                    <ul>
                        <li><fb:intl>Pole position: 10 points</fb:intl></li>
                        <li><fb:intl>1st: 25 points</fb:intl></li>
                        <li><fb:intl>2nd: 18 points</fb:intl></li>
                        <li><fb:intl>3rd: 15 points</fb:intl></li>
                        <li><fb:intl>Correct driver on podium but not in correct position: 8 points for each driver</fb:intl></li>
                        <li><fb:intl>Fastest lap: 10 points</fb:intl></li>
                    </ul>
                </div>
            </div>
            <div class="roundedcornr_bottom_867993"><div></div></div>
        </div>
    </li>
    <li>
        <div class="roundedcornr_box_867993">
            <div class="roundedcornr_top_867993"><div></div></div>
            <div class="roundedcornr_content_867993">
                <img src="<?php echo $this->baseUrl() . '/assets/images/Fav.png' ?>" />
                <h3><fb:intl>The Prize</fb:intl></h3>
                <div class="box-content">
                    <p><fb:intl>The grand prize is a (real) 1:43 scale Minichamps replica of the winning car/driver.</fb:intl></p>
                    <p><fb:intl>A (virtual) trophy is awarded to the player(s) with the highest score each race. You can see your trophies on your profile page</fb:intl></p>
                </div>
            </div>
            <div class="roundedcornr_bottom_867993"><div></div></div>
        </div>
    </li>
</ul>

<center><a target="_top" href="http://www.facebook.com/apps/application.php?v=app_2373072738&id=260355693211">Discussion board</a> | <a target="_top" href="http://www.f1buzz.net">Get the Buzz</a></center>